### ISSUE TITLE
Now problem with click "backup"?

### ISSUE THREAD

**Issue by thearabbit** [hitchcott/app-dump#23]
``` js
http.js:732                                                                                                                                        
    throw new Error('Can\'t render headers after they are sent to the client.'                                                                     
          ^                                                                                                                                        
Error: Can't render headers after they are sent to the client.                                                                                     
  at ServerResponse.OutgoingMessage._renderHeaders (http.js:732:11)                                                                                
  at ServerResponse.writeHead (http.js:1153:20)                                                                                                    
  at ProxyServer.<anonymous> (C:\Users\Theara\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\run-proxy.js:96:21)      
  at ProxyServer.emit (C:\Users\Theara\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\eventemitt
er3\index.js:100:27)                                                                                                                               
  at ClientRequest.proxyError (C:\Users\Theara\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\ht
tp-proxy\lib\http-proxy\passes\web-incoming.js:140:16)                                                                                             
  at ClientRequest.emit (events.js:117:20)                                                                                                         
  at Socket.socketErrorListener (http.js:1552:9)                                                                                                   
  at Socket.emit (events.js:95:17)                                                                                                                 
  at net.js:441:14                                                                                                                                 
  at process._tickCallback (node.js:442:13)                                                                                                        
```

**Comment by thearabbit** [comment]
After I tried many times, I thinks that it have problem with size of db (> 1 Mb)

``` js
W20151002-11:34:00.280(7)? (STDERR)                                                                                                                
W20151002-11:34:00.280(7)? (STDERR) C:\Users\Theara\AppData\Local\.meteor\packages\hitchcott_app-dump\0.4.1\npm\node_modules\mongodb-backup\node_mo
dules\mongodb\lib\utils.js:97                                                                                                                      
W20151002-11:34:00.281(7)? (STDERR)     process.nextTick(function() { throw err; });                                                               
W20151002-11:34:00.281(7)? (STDERR)                                         ^                                                                      
W20151002-11:34:00.281(7)? (STDERR) Error: UNKNOWN, unknown error 'C:\Users\Theara\AppData\Local\.meteor\packages\hitchcott_app-dump\0.4.1\npm\node
_modules\mongodb-backup\dump\meteor\sample_location\0704.bson'                                                                                     
W20151002-11:34:00.281(7)? (STDERR)     at Object.fs.openSync (fs.js:439:18)                                                                       
W20151002-11:34:00.281(7)? (STDERR)     at Object.fs.writeFileSync (fs.js:978:15)                                                                  
W20151002-11:34:00.282(7)? (STDERR)     at C:\Users\Theara\AppData\Local\.meteor\packages\hitchcott_app-dump\0.4.1\npm\node_modules\mongodb-backup\
index.min.js:56:19                                                                                                                                 
W20151002-11:34:00.282(7)? (STDERR)     at Array.forEach (native)                                                                                  
W20151002-11:34:00.282(7)? (STDERR)     at toBson (C:\Users\Theara\AppData\Local\.meteor\packages\hitchcott_app-dump\0.4.1\npm\node_modules\mongodb
-backup\index.min.js:55:37)                                                                                                                        
W20151002-11:34:00.283(7)? (STDERR)     at C:\Users\Theara\AppData\Local\.meteor\packages\hitchcott_app-dump\0.4.1\npm\node_modules\mongodb-backup\
index.min.js:71:82                                                                                                                                 
W20151002-11:34:00.283(7)? (STDERR)     at handleCallback (C:\Users\Theara\AppData\Local\.meteor\packages\hitchcott_app-dump\0.4.1\npm\node_modules
\mongodb-backup\node_modules\mongodb\lib\utils.js:95:12)                                                                                           
W20151002-11:34:00.283(7)? (STDERR)     at C:\Users\Theara\AppData\Local\.meteor\packages\hitchcott_app-dump\0.4.1\npm\node_modules\mongodb-backup\
node_modules\mongodb\lib\cursor.js:772:16                                                                                                          
W20151002-11:34:00.284(7)? (STDERR)     at handleCallback (C:\Users\Theara\AppData\Local\.meteor\packages\hitchcott_app-dump\0.4.1\npm\node_modules
\mongodb-backup\node_modules\mongodb\node_modules\mongodb-core\lib\cursor.js:244:5)                                                                
W20151002-11:34:00.284(7)? (STDERR)     at setCursorDeadAndNotified (C:\Users\Theara\AppData\Local\.meteor\packages\hitchcott_app-dump\0.4.1\npm\no
de_modules\mongodb-backup\node_modules\mongodb\node_modules\mongodb-core\lib\cursor.js:548:3)                                                      
W20151002-11:34:00.284(7)? (STDERR)     at nextFunction (C:\Users\Theara\AppData\Local\.meteor\packages\hitchcott_app-dump\0.4.1\npm\node_modules\m
ongodb-backup\node_modules\mongodb\node_modules\mongodb-core\lib\cursor.js:718:7)                                                                  
W20151002-11:34:00.284(7)? (STDERR)     at [object Object].Cursor.next [as _next] (C:\Users\Theara\AppData\Local\.meteor\packages\hitchcott_app-dum
p\0.4.1\npm\node_modules\mongodb-backup\node_modules\mongodb\node_modules\mongodb-core\lib\cursor.js:749:3)                                        
W20151002-11:34:00.285(7)? (STDERR)     at fetchDocs (C:\Users\Theara\AppData\Local\.meteor\packages\hitchcott_app-dump\0.4.1\npm\node_modules\mong
odb-backup\node_modules\mongodb\lib\cursor.js:768:10)                                                                                              
W20151002-11:34:00.285(7)? (STDERR)     at C:\Users\Theara\AppData\Local\.meteor\packages\hitchcott_app-dump\0.4.1\npm\node_modules\mongodb-backup\
node_modules\mongodb\lib\cursor.js:791:7                                                                                                           
W20151002-11:34:00.285(7)? (STDERR)     at handleCallback (C:\Users\Theara\AppData\Local\.meteor\packages\hitchcott_app-dump\0.4.1\npm\node_modules
\mongodb-backup\node_modules\mongodb\node_modules\mongodb-core\lib\cursor.js:244:5)                                                                
W20151002-11:34:00.285(7)? (STDERR)     at nextFunction (C:\Users\Theara\AppData\Local\.meteor\packages\hitchcott_app-dump\0.4.1\npm\node_modules\m
```

**Comment by thearabbit** [comment]
Now it is OK.
It have problem with `IDM Downloader`.
