### ISSUE TITLE
Issue with MUP deployment

### ISSUE THREAD

**Issue by ytay2** [hitchcott/app-dump#27]
Hi, first of all thanks for this wonderful package.

However, I am facing issues while using this with MUP. I get the following error during deployment (sorry if this is an issue with MUP). but it works on my local copy! 

Thanks in advance, here's the error log! 

```
-----------------------------------STDERR-----------------------------------
npm ERR! Error: version not found: bson@0.4.11
npm ERR!     at /opt/nodejs/lib/node_modules/npm/lib/cache/add-named.js:125:12
npm ERR!     at saved (/opt/nodejs/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-57-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /opt/RedReapers/tmp/bundle/programs/server/npm/hitchcott_app-dump/node_modules/mongodb-backup
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/RedReapers/tmp/bundle/programs/server/npm/hitchcott_app-dump/node_modules/mongodb-backup/npm-debug.log
npm ERR! not ok code 0
-----------------------------------STDOUT-----------------------------------
 > ./mongodb-backup: npm install due to binary npm modules
```

**Comment by hex7c0** [comment]
related with #24

**Comment by IstoraMandiri** [comment]
Is this fixed now in `0.4.2` ?
